In [2]:
import numpy as np
import pandas as pd

### 1. NumPy: Numerical Arrays

- Q1.1: Create a 1D NumPy array with 10 equally spaced values between 0 and 100. Then, reshape this array into a 2x5 matrix.
array_1d = np.linspace(0, 100, 10)
    - Expected Output: A $2 \times 5$ array of floats.

In [3]:
print(np.linspace(0,100,10))

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


- Q1.2: Create a 3x3 array of random integers between 1 and 50. Write code to:

- Find the mean of the entire array.

- Extract the entire second column of the array.

    - Expected Output: The mean value and a 1D array of the second column.

In [5]:
mat = np.random.randint(1,51,size=(3,3))
print(mat)
print(np.mean(mat)) 
print(mat[:,2:3])

[[48 47 12]
 [40  3  3]
 [14 10 43]]
24.444444444444443
[[12]
 [ 3]
 [43]]


### 2. Pandas: DataFrames

In [11]:
# Q2.1: Create a Pandas DataFrame from the following dictionary:
data = {
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard'],
    'Price': [1200, 25, 300, 75],
    'Stock': [10, 50, 0, 22]

}


Display the first 2 rows

In [12]:

df1 = pd.DataFrame(data)
print(df1.head(2))


  Product  Price  Stock
0  Laptop   1200     10
1   Mouse     25     50


Filter the DataFrame to show only products that are out of stock (Stock == 0).

In [13]:
print(df1[df1["Stock"]==0])


   Product  Price  Stock
2  Monitor    300      0


- Q2.2: Using the same DataFrame:
   - Add a new column called Total_Value which is calculated by multiplying Price and Stock.

   - Calculate the total sum of the Total_Value column.

In [14]:
df1['Total_Value'] = df1['Price'] * df1['Stock']
print(df1)
print(df1['Total_Value'].mean())

    Product  Price  Stock  Total_Value
0    Laptop   1200     10        12000
1     Mouse     25     50         1250
2   Monitor    300      0            0
3  Keyboard     75     22         1650
3725.0


### 3. Data Cleaning & Analysis

In [16]:

df = pd.DataFrame({'A': [1, 2, np.nan, 4], 'B': [5, np.nan, 7, 8]})

Fill the missing values (NaN) with the mean of their respective columns.

In [18]:
df = df.fillna(df.mean())
print(df)


          A         B
0  1.000000  5.000000
1  2.000000  6.666667
2  2.333333  7.000000
3  4.000000  8.000000


Drop the rows where the value in column 'A' is greater than 2.

In [20]:
df.drop(df[df['A'] > 2].index, inplace=True)

print(df)

     A         B
0  1.0  5.000000
1  2.0  6.666667
